### PR TITLE
Updated repo to reflect changes in ATK

### PR DESCRIPTION
**Pull request by AaronYoung5**
Made changes relative to an overhaul of atk.

### CODE REVIEW

**Comment by AaronYoung5** [comment]
Must update `autonomy-toolkit` to test.

**Comment by StefanCaldararu** [comment]
I had to set the `COMPOSE_PROJECT_NAME` environment variable manually, but other than that everything worked for me. Do we not want a default value for this?

**Comment by AaronYoung5** [comment]
What version of `docker` and `docker compose` do you have?

**Comment by StefanCaldararu** [comment]
> What version of `docker` and `docker compose` do you have? And what OS?

`docker` version 24.0.6 and `docker-compose` version 1.29.2. I am on Ubuntu 22.04.3

**Comment by AaronYoung5** [comment]
Hmm I can't replicate. What if you call `unset COMPOSE_PROJECT_NAME` before running with atk. And to be clear, you've updated atk to the new version? How about try `docker compose -f atk.yml up -d dev && docker compose -f atk.yml exec dev /bin/bash`.

Also, how do you know it's not set? Like what is the error when you don't set it manually?

**Comment by StefanCaldararu** [comment]
Yes, I updated to 'autonomy-toolkit' to version 2.0.0. here is the output I get without setting the variable:

[out.txt](https://github.com/uwsbel/autonomy-research-testbed/files/12570639/out.txt)

**Comment by StefanCaldararu** [comment]
> Hmm I can't replicate. What if you call `unset COMPOSE_PROJECT_NAME` before running with atk. And to be clear, you've updated atk to the new version? How about try `docker compose -f atk.yml up -d dev && docker compose -f atk.yml exec dev /bin/bash`.

`unset COMPOSE_PROJECT_NAME` yields the same result, and `docker compose -f atk.yml up -d dev && docker compose -f atk.yml exec dev /bin/bash` gives similar warnings - this just runs everything directly through docker compose as opposed to atk, right?

Here are the warnings (sorry I wasn't able to pipe them to a file for some reason...):

`WARN[0000] The "DISPLAY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
Error response from daemon: invalid reference format`

**Comment by AaronYoung5** [comment]
> unset COMPOSE_PROJECT_NAME yields the same result, and docker compose -f atk.yml up -d dev && docker compose -f atk.yml exec dev /bin/bash gives similar warnings - this just runs everything directly through docker compose as opposed to atk, right?

Ya.

This is kinda silly. I can't replicate. To get `docker compose` version, you ran `docker compose version`, not `docker-compose --version`, right? If not, what is the output of `docker compose version`. Should be > v2.12.x.

**Comment by StefanCaldararu** [comment]
> This is kinda silly. I can't replicate. To get `docker compose` version, you ran `docker compose version`, not `docker-compose --version`, right? If not, what is the output of `docker compose version`? Should be > v2.12.x.

Sorry, output `docker compose version` is v2.3.3

**Comment by AaronYoung5** [comment]
> > This is kinda silly. I can't replicate. To get `docker compose` version, you ran `docker compose version`, not `docker-compose --version`, right? If not, what is the output of `docker compose version`? Should be > v2.12.x.
> 
> Sorry, output `docker compose version` is v2.3.3

Okay, looks like you need to update that. Can you try to that and let me know if it works?

**Comment by StefanCaldararu** [comment]
> Okay, looks like you need to update that. Can you try to that and let me know if it works?

Thanks, seems to work now. When I exit the `dev` container I get this message: `CRITICAL | dev._run_cmd :: Failed to run 'attach'.` Is there a reason for this?

**Comment by AaronYoung5** [comment]
> > Okay, looks like you need to update that. Can you try to that and let me know if it works?
> 
> Thanks, seems to work now. When I exit the `dev` container I get this message: `CRITICAL | dev._run_cmd :: Failed to run 'attach'.` Is there a reason for this?

That happened cause when you exit the container, the return code of the most recent command you made is returned. I had initially had a check that would make sure the return code is 0, but in this case, the last command you had run probably returned something other than 0. I just updated atk to not check the return code, so should have fixed that issue.

On another note, is it worth adding a check to make sure docker compose has the correct version in atk?

**Comment by StefanCaldararu** [comment]
> On another note, is it worth adding a check to make sure docker compose has the correct version in atk?

IMO adding it to the documentation (prerequisites section) would make more sense, but up to you...

**Comment by AaronYoung5** [comment]
> > On another note, is it worth adding a check to make sure docker compose has the correct version in atk?
> 
> IMO adding it to the documentation (prerequisites section) would make more sense, but up to you...

Agreed. Will add to atk docs.

**Comment by AaronYoung5** [comment]
> > On another note, is it worth adding a check to make sure docker compose has the correct version in atk?
> 
> IMO adding it to the documentation (prerequisites section) would make more sense, but up to you...

https://github.com/uwsbel/autonomy-toolkit/commit/07aa657fe7f3537a778c3df876dc498fdd5c3188

**Comment by StefanCaldararu** [comment]
How does one set the Display variable? I get the following warning: `WARN[0000] The "DISPLAY" variable is not set. Defaulting to a blank string.` Also wouldn't it make sense to have it default to something like `VNC`?

**Comment by StefanCaldararu** [comment]
I'm having trouble with port forwarding over ssh, I think this is related to the removal of the `--port-mappings`. How do I figure out which port the container ends up mapping to? Also if I ssh with port forwarding, dow this mark the port as being used, in which case launching the container would use a different port (this doesn't make sense to me, but for some reason I am unable to use my 8080 port even though I don't think anything else is using it)...

**Comment by StefanCaldararu** [comment]
> I get the following warning when launching containers over ssh: `WARN[0000] The "DISPLAY" variable is not set. Defaulting to a blank string.` I'm guessing this is used for the vnc visualization or no?

How do I check what port the vnc container is using, as I am no longer able to set this with `--port-mappings`?

**Comment by AaronYoung5** [comment]
> I get the following warning when launching containers over ssh: `WARN[0000] The "DISPLAY" variable is not set. Defaulting to a blank string.` I'm guessing this is used for the vnc visualization or no?

ya not an issue. probably didn't have vnc set.

> I'm having trouble with port forwarding over ssh, I think this is related to the removal of the --port-mappings. How do I figure out which port the container ends up mapping to? Also if I ssh with port forwarding, dow this mark the port as being used, in which case launching the container would use a different port (this doesn't make sense to me, but the only idea I had as to what could be going on)...

Run `atk dev -c ps -s vnc`. See [the tuturial page](https://projects.sbel.org/autonomy-toolkit/tutorials/using-the-development-environment/using-the-development-environment.html#port-mappings) for more details. Under the hood, this is running `docker compose -f <path-to-art>/atk.yml ps vnc`.

**Comment by AaronYoung5** [comment]
@StefanCaldararu review for a review?

**Comment by AaronYoung5** [comment]
@harryzhang1018 @srirama02 while doing the chrono::ros stuff (you'll need to change the dockerfiles to checkout the correct feature branch), might as well try out the new atk. Let me know if you run into any issues, we can try merging this PR

**Comment by StefanCaldararu** [comment]
> @StefanCaldararu review for a review?

@AaronYoung5  Sorry I missed this... I'll take a look at this Saturday

**Review by StefanCaldararu — APPROVED** [review]

**Pull request merged**
