### PR TITLE
fixes to bugs in main

### PR DESCRIPTION
**Pull request by StefanCaldararu**
Temporary fixes to issue #49.

### CODE REVIEW

**Comment by StefanCaldararu** [comment]
@AaronYoung5 Getting the following error when trying to build the sim container: 

`368.2 [1125/1210] Swig compile ../interface/core/ChModuleCore.i for python
368.2 /home/art/chrono/src/chrono_swig/interface/core/../../../chrono/physics/ChSystemSMC.h:49: Warning 314: 'None' is a python keyword, renaming to '_None'
368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:265: Warning 473: Returning a pointer or reference in a director method is not recommended.
368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:328: Warning 473: Returning a pointer or reference in a director method is not recommended.
368.2 ninja: build stopped: subcommand failed.
------
failed to solve: process "/bin/sh -c git clone --recursive -b ${CHRONO_BRANCH} ${CHRONO_REPO} ${CHRONO_DIR} &&     . ${ROS_WORKSPACE_DIR}/install/setup.sh &&     cd ${CHRONO_DIR}/contrib/build-scripts/vsg/ &&     sudo bash buildVSG.sh /opt/vsg &&     cd ${CHRONO_DIR}/contrib/build-scripts/urdf/ &&     sudo bash buildURDF.sh /opt/urdf &&     mkdir ${CHRONO_DIR}/build &&     cd ${CHRONO_DIR}/build &&     cmake ../ -G Ninja         -DCMAKE_BUILD_TYPE=Release         -DBUILD_DEMOS=OFF         -DBUILD_BENCHMARKING=OFF         -DBUILD_TESTING=OFF         -DENABLE_MODULE_VEHICLE=ON         -DENABLE_MODULE_IRRLICHT=ON         -DENABLE_MODULE_PYTHON=ON         -DENABLE_MODULE_SENSOR=ON         -DENABLE_MODULE_ROS=ON         -DENABLE_MODULE_VSG=ON         -DENABLE_MODULE_PARSERS=ON         -DEigen3_DIR=/usr/lib/cmake/eigen3         -DOptiX_INCLUDE=/opt/optix/include         -DOptiX_INSTALL_DIR=/opt/optix         -DUSE_CUDA_NVRTC=OFF         -DNUMPY_INCLUDE_DIR=$(python3 -c 'import numpy; print(numpy.get_include())')         -DCMAKE_INSTALL_PREFIX=${CHRONO_INSTALL_DIR}         -Dvsg_DIR=/opt/vsg/lib/cmake/vsg         -DvsgImGui_DIR=/opt/vsg/lib/cmake/vsgImGui         -DvsgXchange_DIR=/opt/vsg/lib/cmake/vsgXchange         -Durdfdom_DIR=/opt/urdf/lib/urdfdom/cmake         -Durdfdom_headers_DIR=/opt/urdf/lib/urdfdom_headers/cmake         -Dconsole_bridge_DIR=/opt/urdf/lib/console_bridge/cmake         -Dtinyxml2_DIR=/opt/urdf/CMake         &&     ninja && sudo sh -c \". ${ROS_WORKSPACE_DIR}/install/setup.sh; ninja install\"" did not complete successfully: exit code: 1
CRITICAL | dev._run_cmd :: Failed to run 'up' with returncode 17.`

**Comment by StefanCaldararu** [comment]
> @AaronYoung5 Getting the following error when trying to build the sim container:
> 
> ## 368.2 [1125/1210] Swig compile ../interface/core/ChModuleCore.i for python
> 368.2 /home/art/chrono/src/chrono_swig/interface/core/../../../chrono/physics/ChSystemSMC.h:49: Warning 314: 'None' is a python keyword, renaming to '_None'
> 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:265: Warning 473: Returning a pointer or reference in a director method is not recommended.
> 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:328: Warning 473: Returning a pointer or reference in a director method is not recommended.
> 368.2 ninja: build stopped: subcommand failed.
> failed to solve: process "/bin/sh -c git clone --recursive -b ${CHRONO_BRANCH} ${CHRONO_REPO} ${CHRONO_DIR} && . ${ROS_WORKSPACE_DIR}/install/setup.sh && cd ${CHRONO_DIR}/contrib/build-scripts/vsg/ && sudo bash buildVSG.sh /opt/vsg && cd ${CHRONO_DIR}/contrib/build-scripts/urdf/ && sudo bash buildURDF.sh /opt/urdf && mkdir ${CHRONO_DIR}/build && cd ${CHRONO_DIR}/build && cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DEMOS=OFF -DBUILD_BENCHMARKING=OFF -DBUILD_TESTING=OFF -DENABLE_MODULE_VEHICLE=ON -DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_PYTHON=ON -DENABLE_MODULE_SENSOR=ON -DENABLE_MODULE_ROS=ON -DENABLE_MODULE_VSG=ON -DENABLE_MODULE_PARSERS=ON -DEigen3_DIR=/usr/lib/cmake/eigen3 -DOptiX_INCLUDE=/opt/optix/include -DOptiX_INSTALL_DIR=/opt/optix -DUSE_CUDA_NVRTC=OFF -DNUMPY_INCLUDE_DIR=$(python3 -c 'import numpy; print(numpy.get_include())') -DCMAKE_INSTALL_PREFIX=${CHRONO_INSTALL_DIR} -Dvsg_DIR=/opt/vsg/lib/cmake/vsg -DvsgImGui_DIR=/opt/vsg/lib/cmake/vsgImGui -DvsgXchange_DIR=/opt/vsg/lib/cmake/vsgXchange -Durdfdom_DIR=/opt/urdf/lib/urdfdom/cmake -Durdfdom_headers_DIR=/opt/urdf/lib/urdfdom_headers/cmake -Dconsole_bridge_DIR=/opt/urdf/lib/console_bridge/cmake -Dtinyxml2_DIR=/opt/urdf/CMake && ninja && sudo sh -c ". ${ROS_WORKSPACE_DIR}/install/setup.sh; ninja install"" did not complete successfully: exit code: 1 CRITICAL | dev._run_cmd :: Failed to run 'up' with returncode 17.

building sim works from main branch...

**Comment by AaronYoung5** [comment]
> > @AaronYoung5 Getting the following error when trying to build the sim container:
> > ## 368.2 [1125/1210] Swig compile ../interface/core/ChModuleCore.i for python
> > 368.2 /home/art/chrono/src/chrono_swig/interface/core/../../../chrono/physics/ChSystemSMC.h:49: Warning 314: 'None' is a python keyword, renaming to '_None'
> > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:265: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:328: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > 368.2 ninja: build stopped: subcommand failed.
> > failed to solve: process "/bin/sh -c git clone --recursive -b ${CHRONO_BRANCH} ${CHRONO_REPO} ${CHRONO_DIR} && . ${ROS_WORKSPACE_DIR}/install/setup.sh && cd ${CHRONO_DIR}/contrib/build-scripts/vsg/ && sudo bash buildVSG.sh /opt/vsg && cd ${CHRONO_DIR}/contrib/build-scripts/urdf/ && sudo bash buildURDF.sh /opt/urdf && mkdir ${CHRONO_DIR}/build && cd ${CHRONO_DIR}/build && cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DEMOS=OFF -DBUILD_BENCHMARKING=OFF -DBUILD_TESTING=OFF -DENABLE_MODULE_VEHICLE=ON -DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_PYTHON=ON -DENABLE_MODULE_SENSOR=ON -DENABLE_MODULE_ROS=ON -DENABLE_MODULE_VSG=ON -DENABLE_MODULE_PARSERS=ON -DEigen3_DIR=/usr/lib/cmake/eigen3 -DOptiX_INCLUDE=/opt/optix/include -DOptiX_INSTALL_DIR=/opt/optix -DUSE_CUDA_NVRTC=OFF -DNUMPY_INCLUDE_DIR=$(python3 -c 'import numpy; print(numpy.get_include())') -DCMAKE_INSTALL_PREFIX=${CHRONO_INSTALL_DIR} -Dvsg_DIR=/opt/vsg/lib/cmake/vsg -DvsgImGui_DIR=/opt/vsg/lib/cmake/vsgImGui -DvsgXchange_DIR=/opt/vsg/lib/cmake/vsgXchange -Durdfdom_DIR=/opt/urdf/lib/urdfdom/cmake -Durdfdom_headers_DIR=/opt/urdf/lib/urdfdom_headers/cmake -Dconsole_bridge_DIR=/opt/urdf/lib/console_bridge/cmake -Dtinyxml2_DIR=/opt/urdf/CMake && ninja && sudo sh -c ". ${ROS_WORKSPACE_DIR}/install/setup.sh; ninja install"" did not complete successfully: exit code: 1 CRITICAL | dev._run_cmd :: Failed to run 'up' with returncode 17.
> 
> building sim works from main branch...

wym building sim works from main? can you delete the chrono image and then run `docker image prune` (will only remove dangling image, is safe) before rebuilding.

**Comment by AaronYoung5** [comment]
> > > @AaronYoung5 Getting the following error when trying to build the sim container:
> > > ## 368.2 [1125/1210] Swig compile ../interface/core/ChModuleCore.i for python
> > > 368.2 /home/art/chrono/src/chrono_swig/interface/core/../../../chrono/physics/ChSystemSMC.h:49: Warning 314: 'None' is a python keyword, renaming to '_None'
> > > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:265: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:328: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > > 368.2 ninja: build stopped: subcommand failed.
> > > failed to solve: process "/bin/sh -c git clone --recursive -b ${CHRONO_BRANCH} ${CHRONO_REPO} ${CHRONO_DIR} && . ${ROS_WORKSPACE_DIR}/install/setup.sh && cd ${CHRONO_DIR}/contrib/build-scripts/vsg/ && sudo bash buildVSG.sh /opt/vsg && cd ${CHRONO_DIR}/contrib/build-scripts/urdf/ && sudo bash buildURDF.sh /opt/urdf && mkdir ${CHRONO_DIR}/build && cd ${CHRONO_DIR}/build && cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DEMOS=OFF -DBUILD_BENCHMARKING=OFF -DBUILD_TESTING=OFF -DENABLE_MODULE_VEHICLE=ON -DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_PYTHON=ON -DENABLE_MODULE_SENSOR=ON -DENABLE_MODULE_ROS=ON -DENABLE_MODULE_VSG=ON -DENABLE_MODULE_PARSERS=ON -DEigen3_DIR=/usr/lib/cmake/eigen3 -DOptiX_INCLUDE=/opt/optix/include -DOptiX_INSTALL_DIR=/opt/optix -DUSE_CUDA_NVRTC=OFF -DNUMPY_INCLUDE_DIR=$(python3 -c 'import numpy; print(numpy.get_include())') -DCMAKE_INSTALL_PREFIX=${CHRONO_INSTALL_DIR} -Dvsg_DIR=/opt/vsg/lib/cmake/vsg -DvsgImGui_DIR=/opt/vsg/lib/cmake/vsgImGui -DvsgXchange_DIR=/opt/vsg/lib/cmake/vsgXchange -Durdfdom_DIR=/opt/urdf/lib/urdfdom/cmake -Durdfdom_headers_DIR=/opt/urdf/lib/urdfdom_headers/cmake -Dconsole_bridge_DIR=/opt/urdf/lib/console_bridge/cmake -Dtinyxml2_DIR=/opt/urdf/CMake && ninja && sudo sh -c ". ${ROS_WORKSPACE_DIR}/install/setup.sh; ninja install"" did not complete successfully: exit code: 1 CRITICAL | dev._run_cmd :: Failed to run 'up' with returncode 17.
> > 
> > 
> > building sim works from main branch...
> 
> wym building sim works from main? can you delete the chrono image and then run `docker system prune` (will only remove unused stuff, should be safe) before rebuilding.

i see a bug too. trying to fix

**Comment by StefanCaldararu** [comment]
> > > @AaronYoung5 Getting the following error when trying to build the sim container:
> > > ## 368.2 [1125/1210] Swig compile ../interface/core/ChModuleCore.i for python
> > > 368.2 /home/art/chrono/src/chrono_swig/interface/core/../../../chrono/physics/ChSystemSMC.h:49: Warning 314: 'None' is a python keyword, renaming to '_None'
> > > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:265: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > > 368.2 /home/art/chrono/src/chrono/../chrono/physics/ChLoad.h:328: Warning 473: Returning a pointer or reference in a director method is not recommended.
> > > 368.2 ninja: build stopped: subcommand failed.
> > > failed to solve: process "/bin/sh -c git clone --recursive -b ${CHRONO_BRANCH} ${CHRONO_REPO} ${CHRONO_DIR} && . ${ROS_WORKSPACE_DIR}/install/setup.sh && cd ${CHRONO_DIR}/contrib/build-scripts/vsg/ && sudo bash buildVSG.sh /opt/vsg && cd ${CHRONO_DIR}/contrib/build-scripts/urdf/ && sudo bash buildURDF.sh /opt/urdf && mkdir ${CHRONO_DIR}/build && cd ${CHRONO_DIR}/build && cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DEMOS=OFF -DBUILD_BENCHMARKING=OFF -DBUILD_TESTING=OFF -DENABLE_MODULE_VEHICLE=ON -DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_PYTHON=ON -DENABLE_MODULE_SENSOR=ON -DENABLE_MODULE_ROS=ON -DENABLE_MODULE_VSG=ON -DENABLE_MODULE_PARSERS=ON -DEigen3_DIR=/usr/lib/cmake/eigen3 -DOptiX_INCLUDE=/opt/optix/include -DOptiX_INSTALL_DIR=/opt/optix -DUSE_CUDA_NVRTC=OFF -DNUMPY_INCLUDE_DIR=$(python3 -c 'import numpy; print(numpy.get_include())') -DCMAKE_INSTALL_PREFIX=${CHRONO_INSTALL_DIR} -Dvsg_DIR=/opt/vsg/lib/cmake/vsg -DvsgImGui_DIR=/opt/vsg/lib/cmake/vsgImGui -DvsgXchange_DIR=/opt/vsg/lib/cmake/vsgXchange -Durdfdom_DIR=/opt/urdf/lib/urdfdom/cmake -Durdfdom_headers_DIR=/opt/urdf/lib/urdfdom_headers/cmake -Dconsole_bridge_DIR=/opt/urdf/lib/console_bridge/cmake -Dtinyxml2_DIR=/opt/urdf/CMake && ninja && sudo sh -c ". ${ROS_WORKSPACE_DIR}/install/setup.sh; ninja install"" did not complete successfully: exit code: 1 CRITICAL | dev._run_cmd :: Failed to run 'up' with returncode 17.
> > 
> > 
> > building sim works from main branch...
> 
> wym building sim works from main? can you delete the chrono image and then run `docker system prune` (will only remove unused stuff, should be safe) before rebuilding.

ya thats what im doing

**Comment by AaronYoung5** [comment]
@StefanCaldararu pushed the fix, sorry

**Comment by StefanCaldararu** [comment]
> @StefanCaldararu pushed the fix, sorry

seems to be working for me! Any more permanent fix to #46? Otherwise good to push 👍

**Comment by AaronYoung5** [comment]
> > @StefanCaldararu pushed the fix, sorry
> 
> seems to be working for me! Any more permanent fix to #46? Otherwise good to push 👍

that is the permanent fix imo unfortunately.

**Review by StefanCaldararu — COMMENTED** [review]
Looks good to me, @AaronYoung5 you're gonna have to approve / merge yourself when you're happy with this.

**Review by AaronYoung5 — APPROVED** [review]

**Pull request merged**
