### PR TITLE
Minor updates to dev container.

### PR DESCRIPTION
**Pull request by AaronYoung5**
Includes the following updates:
- Update galactic to humble
- Updated python in the container to `3.10`
- Removed the unused `pip-pychrono` container

### CODE REVIEW

**Comment by StefanCaldararu** [comment]
IMO we should use Humble as the base as it is the stable release, and have an Iron branch that is for testing the event executioner...

**Comment by AaronYoung5** [comment]
> IMO we should use Humble as the base as it is the stable release, and have an Iron branch that is for testing the event executioner...

Updated

**Comment by StefanCaldararu** [comment]
I get the following error with colcon build once inside of the d
[build_error.txt](https://github.com/uwsbel/autonomy-research-testbed/files/12377179/build_error.txt)
ev container.

**Review by StefanCaldararu — APPROVED** [review]
My tests of these changes worked and everything can be merged from my end

**Pull request merged**
