### PR TITLE
Vehicle specific services

### PR DESCRIPTION
**Pull request by AaronYoung5**
#59

### CODE REVIEW

**Comment by AaronYoung5** [comment]
@harryzhang1018 @ishaanamahajan @srirama02 @zzhou292 I added a demo vehicle specific service called `art5`. The docs on how to use are [here](https://github.com/uwsbel/autonomy-research-testbed/blob/master/docs/misc/vehicle_computers.md). Please read through the docs and run the setup script on your vehicles. 

There's also a lot more docs in main now, so please take some time to review if you get the chance. **If you run into issues or feel something else should be in the docs, PLEASE PLEASE write it yourself and open a PR. I don't want to be the only person writing docs. It really sucks.**

> [!NOTE]
> Before running, make sure you delete the `~/sbel` folder if it exists.

@StefanCaldararu for visibility.

**Comment by harryzhang1018** [comment]
@AaronYoung5 Did you fix the git remote orgin issue?

**Comment by AaronYoung5** [comment]
just did @harryzhang1018

**Review by harryzhang1018 — DISMISSED** [review]

**Review by StefanCaldararu — APPROVED** [review]
fire

**Comment by Huzaifg** [comment]
1) This assumes that the OS and autonomy-research-testbed is on the same SSD. This is not the case for us (which is a conscious choice) - I don't think we (ART-Broly) would like to change that. 
2)  We have already done the steps that are outlined in the "setup.sh" script. They are slightly different, but I do not see why each vehicle should be set up exactly the same way, specially for stuff like where the art repo is etc.

**Comment by AaronYoung5** [comment]
> 1. This assumes that the OS and autonomy-research-testbed is on the same SSD. This is not the case for us (which is a conscious choice) - I don't think we (ART-Broly) would like to change that.
> 2. We have already done the steps that are outlined in the "setup.sh" script. They are slightly different, but I do not see why each vehicle should be set up exactly the same way, specially for stuff like where the art repo is etc.

1. I don't believe that is true (that is that this assumes it's on the same SSD). How would that be different? But also had this discussion with @deepak-rlv. It's not clear to me why we don't just use the nvme SSD as the boot device. The only reason NVIDIA includes the emmc SSD is because it's much cheaper, but in all other ways, it's worse.
2. From a development perspective, you/we are not the only users of each vehicle. For instance, if Ishaan is working with Harry on a project with his vehicle (which he has), if everything is _identical_ (in terms of setup), that is ideal/what we want. Plus from a maintenance perspective, it's unclear to me what the advantage of having different setups on each vehicle is.

@Huzaifg thoughts?

**Pull request merged**
