### PR TITLE
Added pre-commit hooks.

### PR DESCRIPTION
**Pull request by AaronYoung5**
Added automatic hooks that will run on any commit. I also added a github action that will run on PR merges to master. 

To test, you must install `pre-commit` (`pip install pre-commit`).

NOTE: I think this is a good idea, others may not. If you have clarifying questions, please ask.

This PR is big because I ran file formatting on all files.

See #7.

### CODE REVIEW

**Comment by AaronYoung5** [comment]
@StefanCaldararu added pre-commit and ran code formatting on all the code. Don't really need to look at the code (imo).

**Comment by StefanCaldararu** [comment]
@AaronYoung5 Bunch of questions, just for my own knowledge :)

- What files were actually changed here outside of the configuration? So I can look?
- What's the benefit of using this over just a standard file formatter?
- is the requirement for pre-commit to be run only for when you merge? so can I push to my PR branch without running pre-commit, and then only on the last commit format stuff and then merge?

**Comment by StefanCaldararu** [comment]
@AaronYoung5 what are reasons someone wouldn't want to use this?

**Comment by AaronYoung5** [comment]
> @AaronYoung5 what are reasons someone wouldn't want to use this?

big devils advocate guy? makes you fix code if it doesn't fit the pre-commit requirements. could fail ig if it gets confused or you add files that you don't want to get checked. steeper learning curve - someone first coming into the repo may not know what pre-commit is and be confused. maybe chatgpt will have better answers.

**Review by StefanCaldararu — APPROVED** [review]
Can't test this on my machine atm, but sounds like a good idea to me. ✅

**Pull request merged**
